import type { WorkflowStepSnapshot } from "./types.js";

export const DEFAULT_WORKFLOW: WorkflowStepSnapshot[] = [
  {
    name: "Decompose",
    description: "Decomposer agent analyzes the feature and breaks it into implementation tasks",
    sort_order: 0,
    exit_criteria: { programmatic: ["all_tasks_complete"], description: "Feature decomposed into task graph" },
    failure_policy: { action: "fail_plan", description: "Decomposition failure aborts the plan" },
    agent_config: { skill: "decomposer", model_tier: "opus", docker_image: "ao-agent:latest" },
    is_conditional: false,
    condition: null,
  },
  {
    name: "Implement",
    description: "Implementation agents work on tasks in parallel",
    sort_order: 1,
    exit_criteria: { programmatic: ["all_tasks_complete"], description: "All implementation tasks done with PRs" },
    failure_policy: { action: "spawn_doctor", max_retries: 2, description: "Doctor heals failed tasks" },
    agent_config: { skill: "fullstack", model_tier: "sonnet", docker_image: "ao-agent:latest" },
    is_conditional: false,
    condition: null,
  },
  {
    name: "Test",
    description: "Integration test agent validates combined changes",
    sort_order: 2,
    exit_criteria: { programmatic: ["all_tasks_complete"], description: "Integration tests pass" },
    failure_policy: { action: "spawn_doctor", max_retries: 1, description: "Doctor fixes test failures" },
    agent_config: { skill: "testing", model_tier: "sonnet", docker_image: "ao-agent-frontend:latest" },
    is_conditional: false,
    condition: null,
  },
  {
    name: "Verify",
    description: "Verify build agent confirms everything compiles and passes",
    sort_order: 3,
    exit_criteria: { programmatic: ["all_tasks_complete"], description: "Build verification passes" },
    failure_policy: { action: "fail_plan", description: "Build failure requires manual intervention" },
    agent_config: { skill: "fullstack", model_tier: "sonnet", docker_image: "ao-agent:latest" },
    is_conditional: false,
    condition: null,
  },
  {
    name: "Complete",
    description: "Merge PRs and cleanup resources",
    sort_order: 4,
    exit_criteria: { programmatic: ["all_tasks_complete"], description: "PRs merged, resources cleaned" },
    failure_policy: { action: "notify", description: "Merge failures need manual resolution" },
    agent_config: { skill: "fullstack", model_tier: "haiku" },
    is_conditional: false,
    condition: null,
  },
];
