import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

// ============================================================================
// MERGE ORCHESTRATOR
// Runs on the host after plan_complete to create a consolidated PR
// ============================================================================

export interface MergeOrchestratorConfig {
  /** Delete individual task branches after merge (local + remote) */
  cleanupBranches: boolean;
  /** Delete integration test branch after PR creation */
  cleanupTestBranch: boolean;
  /** Base branch to target the PR against */
  baseBranch: string;
  /** Draft PR instead of ready */
  draft: boolean;
}

export const DEFAULT_MERGE_CONFIG: MergeOrchestratorConfig = {
  cleanupBranches: true,
  cleanupTestBranch: true,
  baseBranch: "main",
  draft: false,
};

export interface MergeInput {
  planId: string;
  featureDescription: string;
  /** owner/repo format */
  repo: string;
  /** Local path to the repo */
  repoPath: string;
  /** Branch names from completed tasks */
  taskBranches: string[];
  /** Integration test branch (if it exists) */
  integrationBranch: string | null;
}

export interface MergeResult {
  success: boolean;
  /** The feature branch that was pushed */
  featureBranch: string;
  /** PR URL if created */
  prUrl?: string;
  /** Error message if failed */
  error?: string;
  /** Branches that were cleaned up */
  cleanedBranches: string[];
}

async function git(
  repoPath: string,
  ...args: string[]
): Promise<string> {
  const { stdout } = await execFileAsync("git", args, {
    cwd: repoPath,
    timeout: 30_000,
  });
  return stdout.trim();
}

async function gh(
  repoPath: string,
  ...args: string[]
): Promise<string> {
  const { stdout } = await execFileAsync("gh", args, {
    cwd: repoPath,
    timeout: 30_000,
  });
  return stdout.trim();
}

export async function createFeaturePR(
  input: MergeInput,
  config: Partial<MergeOrchestratorConfig> = {},
): Promise<MergeResult> {
  const cfg = { ...DEFAULT_MERGE_CONFIG, ...config };
  const cleanedBranches: string[] = [];

  // The feature branch name for the consolidated PR
  const featureBranch = `feat/${input.planId}`;

  try {
    // If integration test branch exists, it already has all task branches merged.
    // Rename/reuse it as the feature branch.
    if (input.integrationBranch) {
      // Fetch latest from remote
      await git(input.repoPath, "fetch", "origin");

      // Check if integration branch exists locally
      const localBranches = await git(input.repoPath, "branch", "--list", input.integrationBranch);

      if (localBranches) {
        // Create feature branch from the integration branch
        await git(input.repoPath, "branch", "-f", featureBranch, input.integrationBranch);
      } else {
        // Try remote
        const remoteBranch = `origin/${input.integrationBranch}`;
        await git(input.repoPath, "branch", "-f", featureBranch, remoteBranch);
      }
    } else {
      // No integration branch — merge task branches ourselves
      await git(input.repoPath, "fetch", "origin");
      await git(input.repoPath, "checkout", "-B", featureBranch, `origin/${cfg.baseBranch}`);

      for (const branch of input.taskBranches) {
        // Try local first, then remote
        try {
          await git(input.repoPath, "merge", "--no-edit", branch);
        } catch {
          await git(input.repoPath, "merge", "--no-edit", `origin/${branch}`);
        }
      }
    }

    // Push the feature branch
    await git(input.repoPath, "push", "-u", "origin", featureBranch);

    // Build PR body
    const taskList = input.taskBranches.map((b) => `- \`${b}\``).join("\n");
    const body = [
      `## Summary`,
      ``,
      input.featureDescription,
      ``,
      `## Task Branches`,
      taskList,
      ``,
      `## Plan`,
      `Plan ID: \`${input.planId}\``,
      ``,
      `---`,
      `Generated by Agent Orchestrator`,
    ].join("\n");

    // Create PR
    const prArgs = [
      "pr", "create",
      "--repo", input.repo,
      "--head", featureBranch,
      "--base", cfg.baseBranch,
      "--title", `feat: ${input.featureDescription.slice(0, 60)}`,
      "--body", body,
    ];
    if (cfg.draft) {
      prArgs.push("--draft");
    }

    const prUrl = await gh(input.repoPath, ...prArgs);

    // Cleanup task branches
    if (cfg.cleanupBranches) {
      for (const branch of input.taskBranches) {
        try {
          await git(input.repoPath, "push", "origin", "--delete", branch);
          cleanedBranches.push(branch);
        } catch {
          // Branch may not exist on remote — that's fine
        }
        try {
          await git(input.repoPath, "branch", "-D", branch);
        } catch {
          // May not exist locally
        }
      }
    }

    // Cleanup integration test branch
    if (cfg.cleanupTestBranch && input.integrationBranch) {
      try {
        await git(input.repoPath, "push", "origin", "--delete", input.integrationBranch);
        cleanedBranches.push(input.integrationBranch);
      } catch {
        // May not exist
      }
      try {
        await git(input.repoPath, "branch", "-D", input.integrationBranch);
      } catch {
        // May not exist locally
      }
    }

    return {
      success: true,
      featureBranch,
      prUrl,
      cleanedBranches,
    };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return {
      success: false,
      featureBranch,
      error: msg,
      cleanedBranches,
    };
  }
}
